### PR TITLE
linkify comments; add download btn to mixtape show page

### PR DESCRIPTION
**Pull request by ktravers**

### CODE REVIEW

**Comment by dpatti** [comment]
Thanks Kate! It looks like you may have squashed two commits, but only the message from the latter stuck around. Could you change the commit message back to something like what you have in the pull request title? Also, I think you should check in the Gemfile.lock changes since this isn't a library and it's good to have the tested library versions under source control.

**Comment by ktravers** [comment]
No problem; I'm working at a conference today, but I'll change the message
and check in the Gemfile.lock later tonight.

On Tuesday, May 12, 2015, Doug Patti <notifications@github.com> wrote:

> Thanks Kate! It looks like you may have squashed two commits, but only the
> message from the latter stuck around. Could you change the commit message
> back to something like what you have in the pull request title? Also, I
> think you should check in the Gemfile.lock changes since this isn't a
> library and it's good to have the tested library versions under source
> control.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpatti/mixtapes/pull/4#issuecomment-101292244>.
>


-- 
best,
Kate

Kate Travers
646.402.4500  |  travers.kt@gmail.com  |  www.kate-travers.com

**Comment by ktravers** [comment]
All set! Commit message has been amended + Gemfile.lock checked in.

**Comment by dpatti** [comment]
Great, thanks!

**Pull request merged**
